scopes:
    company:
      label: Company
      modelClass: Logingrupa\Studybook\Models\Company
      conditions: company_id in (:value)
      nameFrom: name
    # student_id:
    #    label: Student
    #    modelClass: Rainlab\User\Models\User
    #    conditions: student_id in (:filtered)
    #    nameFrom: name

#    transaction_at:
#        label: 'lovata.toolbox::lang.field.created_at'
#        type: date
#        conditions: transaction_at >= ':filtered'
#    created_at:
#        label: 'lovata.toolbox::lang.field.created_at'
#        type: daterange
#        conditions: created_at >= ':after' AND created_at <= ':before'
#    updated_at:
#        label: 'lovata.toolbox::lang.field.updated_at'
#        type: daterange
#        conditions: updated_at >= ':after' AND updated_at <= ':before'
